import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music-Classes",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <>
      <html lang="en" className="dark">
        <body className={inter.className}>
          <div className="relative w-full flex items-center justify-center ">
            <Navbar />
          </div>

          {children}
        </body>
      </html>
    </>
  );
};

export default RootLayout;
